// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doxrntuyagaesyrxyhcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRveHJudHV5YWdhZXN5cnh5aGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMjY3MTIsImV4cCI6MjA2NjkwMjcxMn0.kRp3wZLJozto__CVCOR15c2MfPBvLwoJwMWmPBs7uKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
